/* Archivo Gótico Modular: la vista previa Unicode y el resultado copiable guían cada interacción; los controles permanecen sobrios y claros. */
// Archivo Gótico Modular: los materiales fríos usan una progresión asimétrica de cian, hielo, brillo blanco, grafito y azul profundo.
const scriptUpper = "𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩";
const scriptLower = "𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝔀𝔁𝔂𝔃";
const frakturUpper = "𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ";
const frakturLower = "𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷";
const monoUpper = "𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅";
const monoLower = "𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟";

const styles = {
  script: { label: "Script", apply: (text) => unicodeMap(text, scriptUpper, scriptLower) },
  fraktur: { label: "Fraktur", apply: (text) => unicodeMap(text, frakturUpper, frakturLower) },
  mono: { label: "Gótico ancho", apply: (text) => unicodeMap(text, monoUpper, monoLower) },
  clean: { label: "Limpio", apply: (text) => text.trim() },
};

const rolePalettes = {
  creator: { label: "Creador", description: "Violeta editorial para distinguir a quienes publican sin parecer staff.", colors: [["#C77DFF", "Violeta Creador"], ["#F7A8D7", "Rosa Clip"], ["#8E9AFF", "Azul Streaming"], ["#E5B65E", "Ámbar Comunidad"]] },
  member: { label: "Comunidad", description: "Verdes y azules amables para presencia comunitaria y conversación.", colors: [["#5BCE96", "Verde Miembro"], ["#75D9E6", "Celeste Social"], ["#A6E3A1", "Menta Amistosa"], ["#B7C7F7", "Azul Suave"]] },
  verified: { label: "Verificación", description: "Verde claro: comunica acceso confirmado sin competir con el staff.", colors: [["#57F287", "Verde Verificado"], ["#5BCE96", "Verde Vitrial"], ["#9AE6B4", "Menta Confirmada"], ["#73DACA", "Turquesa Seguro"]] },
  editor: { label: "Producción", description: "Tonos minerales cálidos para recursos, edición y piezas de contenido.", colors: [["#E89A57", "Cobre Editor"], ["#E5B65E", "Oro Mate"], ["#D9876A", "Coral Archivo"], ["#8ED1B2", "Menta Técnica"]] },
  staff: { label: "Staff", description: "Color de atención para responsabilidades operativas, no para adornar perfiles.", colors: [["#ED4245", "Rojo Staff"], ["#E66A7A", "Rosa Moderación"], ["#F0B85D", "Ámbar Gestión"], ["#7DA4FF", "Azul Operación"]] },
  personal: { label: "Personalizado", description: "Tonos expresivos para identidad sin sugerir jerarquía o permiso.", colors: [["#C77DFF", "Lila Personal"], ["#F38BA8", "Rosa Personal"], ["#89DCEB", "Aqua Personal"], ["#F9E2AF", "Dorado Personal"]] },
  age: { label: "Acceso protegido", description: "Tonos discretos para segmentación por edad; evita usarlos como premio o jerarquía.", colors: [["#9AA5B1", "Gris Acceso"], ["#8294C4", "Azul Calma"], ["#B8A1CE", "Malva Suave"], ["#83B6A6", "Verde Control"]] },
};

const gradientStyles = {
  soft: { label: "Suave", description: "Transición de luz a sombra para un degradado sencillo de dos colores. Mantiene el valor inicial de 2 paradas.", phases: [[0, 0, 24], [0, 0, 0], [0, 0, -26]], twoStop: [0, 2], defaultStops: 2 },
  metal: { label: "Metálico", description: "Una secuencia fría y asimétrica: color vivo, azul hielo, brillo blanco azulado, grafito y azul marino. Es la progresión tonal de referencia, no una rampa de un solo tono.", phases: [[0, 0, 0], [0, -12, 24], [-2, -52, 42], [8, -70, -41], [32, -12, -24]], twoStop: [0, 4], defaultStops: 5 },
  chrome: { label: "Cromado", description: "Comparte la lectura fría de la referencia, pero desatura el cuerpo para pasar de plata azulada a grafito y terminar en azul profundo.", phases: [[0, -28, -3], [-2, -44, 24], [-4, -68, 43], [8, -78, -39], [32, -32, -22]], twoStop: [0, 4], defaultStops: 5 },
  gold: { label: "Oro / mineral", description: "Sombra marrón-negra, cobre cálido, reflejo dorado central y cierre profundo. Conserva la forma de metal aunque el color base cambie.", phases: [[-16, 2, -49], [-12, 11, -25], [-7, 12, 0], [-2, -2, 33], [-7, 8, 10], [-12, 10, -23], [-16, 2, -49]], twoStop: [0, 3], defaultStops: 5 },
  aurora: { label: "Aurora", description: "Oscuros azules y violetas en los extremos, colores vivos en el cuerpo y brillo central. Tiene forma luminosa, no solo cambio de tono.", phases: [[-30, 8, -47], [-18, 14, -19], [4, 16, 4], [30, -4, 30], [14, 13, 11], [-8, 8, -20], [-28, 7, -44]], twoStop: [0, 3], defaultStops: 5 },
  matte: { label: "Mate", description: "Sombras suaves en los lados y una luz central contenida, sin reflejo blanco. Es la variante editorial para roles discretos.", phases: [[0, -42, -35], [0, -34, -15], [0, -30, -1], [0, -38, 15], [0, -32, 0], [0, -37, -16], [0, -42, -35]], twoStop: [0, 3], defaultStops: 5 },
};

const modeData = {
  role: { kicker: "Constructor de roles", title: "Dale personalidad a tu jerarquía.", help: "El nombre que quieres convertir en rol.", initial: "Creador de Contenido", note: "Usa este nombre en Ajustes del servidor > Roles.", styles: ["script", "fraktur", "mono", "clean"], format: (text) => `『 ${text} 』`, previewClass: "role-preview" },
  divider: { kicker: "Constructor de separadores", title: "Ordena sin llenar tu lista de ruido.", help: "El bloque que quieres separar en tu lista de roles.", initial: "Staff", note: "Úsalo como un rol visual sin permisos ni acceso a canales.", styles: ["script", "fraktur", "mono", "clean"], format: (text, style) => ({ script: `«──────『 ${text} 』──────»`, fraktur: `╺━━『 ${text} 』━━╸`, mono: `┄┄┄┄┄ ${text} ┄┄┄┄┄`, clean: `─── ${text} ───` })[style], previewClass: "divider-preview" },
  category: { kicker: "Constructor de categorías", title: "Haz que cada zona se vea intencional.", help: "El nombre de la categoría de canales.", initial: "Información", note: "Pega el resultado al crear o editar una categoría de Discord.", styles: ["script", "fraktur", "mono", "clean"], format: (text, style) => ({ script: `▶ 『 ${text} 』`, fraktur: `✦ 『 ${text} 』`, mono: `┌ ${text} ┐`, clean: `── ${text} ──` })[style], previewClass: "category-preview" },
  channel: { kicker: "Constructor de canales", title: "Elige un emoji y deja clara la intención.", help: "El nombre del canal sin el emoji.", initial: "General", note: "Discord añadirá su icono de tipo de canal; el emoji es parte de tu estilo.", styles: ["script", "fraktur", "mono", "clean"], format: (text, style, emoji) => ({ script: `${emoji}➡『${text}』`, fraktur: `${emoji}・${text}`, mono: `${emoji}｜${text}`, clean: `${emoji}・${text}` })[style], previewClass: "channel-preview" },
  gradient: { kicker: "Generador de degradados", title: "Un color base. El resto se forja solo.", help: "Ajusta el color, el acabado y la cantidad de paradas.", initial: "", note: "Copia el CSS para fondos, embeds o referencias visuales; el color normal de un rol de Discord es plano.", styles: [], previewClass: "gradient-preview" },
};

const channelSuggestions = { general: { emoji: "💬", name: "General" }, info: { emoji: "👋", name: "Bienvenidas" }, rules: { emoji: "📜", name: "Reglas" }, announcements: { emoji: "🔔", name: "Notificaciones" }, verify: { emoji: "✅", name: "Verificación" }, media: { emoji: "📸", name: "Multimedia" }, economy: { emoji: "💰", name: "Economía" }, tickets: { emoji: "🎫", name: "Tickets" }, applications: { emoji: "📂", name: "Postulaciones" }, voice: { emoji: "🔊", name: "Únete para Crear" }, staff: { emoji: "📝", name: "Chat de Staff" } };
const presets = [
  { mode: "role", text: "Creador de Contenido", style: "script", roleType: "creator", label: "Rol de creador", description: "Reconocimiento sin permisos" },
  { mode: "role", text: "Verificado", style: "fraktur", roleType: "verified", label: "Rol de acceso", description: "Después de la verificación" },
  { mode: "divider", text: "Staff", style: "script", label: "Separador", description: "Divide la jerarquía visual" },
  { mode: "category", text: "Información", style: "script", label: "Categoría", description: "Como tu estructura actual" },
  { mode: "channel", text: "General", emoji: "💬", style: "script", channelType: "general", label: "Canal social", description: "Chat principal" },
  { mode: "channel", text: "Tickets", emoji: "🎫", style: "script", channelType: "tickets", label: "Canal de soporte", description: "Atención ordenada" },
  { mode: "channel", text: "Assets-Editores", emoji: "📁", style: "script", channelType: "media", label: "Recurso limitado", description: "Para tus editores" },
  { mode: "gradient", gradientStyle: "metal", baseColor: "#16B8E9", stops: 5, label: "Degradado frío", description: "Cian, hielo, blanco, grafito y azul profundo" },
];

const lightnessModes = {
  dark: { label: "Oscuro", offset: -24, note: "Sombras más profundas y un reflejo central contenido.", previewNote: "Acabado oscuro, sin borde." },
  balanced: { label: "Equilibrado", offset: 0, note: "El punto medio entre sombra y reflejo; recomendado para empezar.", previewNote: "El color vive dentro del texto." },
  light: { label: "Claro", offset: 15, note: "Brillo más alto, conservando las sombras laterales del material.", previewNote: "Acabado claro, sin borde." },
};
const state = { mode: "role", style: "script", text: "Creador de Contenido", emoji: "💬", roleType: "creator", channelType: "general", color: "#C77DFF", baseColor: "#16B8E9", gradientStyle: "metal", gradientDirection: "135deg", gradientLightness: "balanced", gradientStops: 5 };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const clamp = (value, min, max) => Math.min(max, Math.max(min, value));

function unicodeMap(text, uppercase, lowercase) { return [...text].map((character) => { const upperIndex = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(character); const lowerIndex = "abcdefghijklmnopqrstuvwxyz".indexOf(character); if (upperIndex >= 0) return [...uppercase][upperIndex]; if (lowerIndex >= 0) return [...lowercase][lowerIndex]; return character; }).join(""); }
function hexToHsl(hex) { const value = hex.replace("#", ""); const r = parseInt(value.slice(0, 2), 16) / 255; const g = parseInt(value.slice(2, 4), 16) / 255; const b = parseInt(value.slice(4, 6), 16) / 255; const max = Math.max(r, g, b); const min = Math.min(r, g, b); let h = 0; let s = 0; const l = (max + min) / 2; const d = max - min; if (d) { s = d / (1 - Math.abs(2 * l - 1)); if (max === r) h = 60 * (((g - b) / d) % 6); else if (max === g) h = 60 * ((b - r) / d + 2); else h = 60 * ((r - g) / d + 4); } return [(h + 360) % 360, s * 100, l * 100]; }
function hslToHex(h, s, l) { const saturation = s / 100; const light = l / 100; const c = (1 - Math.abs(2 * light - 1)) * saturation; const x = c * (1 - Math.abs((h / 60) % 2 - 1)); const m = light - c / 2; const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x]; return `#${[r, g, b].map((part) => Math.round((part + m) * 255).toString(16).padStart(2, "0")).join("").toUpperCase()}`; }
function gradientColors() {
  const [h, s, l] = hexToHsl(state.baseColor);
  const definition = gradientStyles[state.gradientStyle];
  const phases = definition.phases;
  const lightnessOffset = lightnessModes[state.gradientLightness].offset;
  if (state.gradientStops === 2 && definition.twoStop) return definition.twoStop.map((phaseIndex) => { const phase = phases[phaseIndex]; return hslToHex((h + phase[0] + 360) % 360, clamp(s + phase[1], 8, 100), clamp(l + phase[2] + lightnessOffset, 4, 95)); });
  return Array.from({ length: state.gradientStops }, (_, index) => {
    const progress = state.gradientStops === 1 ? 0 : index / (state.gradientStops - 1);
    const position = progress * (phases.length - 1);
    const lowerIndex = Math.floor(position);
    const upperIndex = Math.min(phases.length - 1, Math.ceil(position));
    const mix = position - lowerIndex;
    const phase = phases[lowerIndex].map((value, phaseIndex) => value + (phases[upperIndex][phaseIndex] - value) * mix);
    return hslToHex((h + phase[0] + 360) % 360, clamp(s + phase[1], 8, 100), clamp(l + phase[2] + lightnessOffset, 4, 95));
  });
}
function gradientCss() { const colors = gradientColors(); return `linear-gradient(${state.gradientDirection}, ${colors.map((color, index) => `${color} ${Math.round((index / (colors.length - 1)) * 100)}%`).join(", ")})`; }
function toneColor(modeKey) { const [h, s, l] = hexToHsl(state.baseColor); const offset = lightnessModes[modeKey].offset; return hslToHex(h, clamp(s - 8, 8, 100), clamp(l + offset, 5, 94)); }
function renderToneSwatches() { const rail = $("#gradient-tone-swatches"); const choices = Object.entries(lightnessModes); rail.innerHTML = choices.map(([key, tone]) => `<button class="tone-swatch ${state.gradientLightness === key ? "is-selected" : ""}" type="button" data-tone="${key}" style="--tone-color:${toneColor(key)}" role="radio" aria-checked="${state.gradientLightness === key}" aria-label="${tone.label}: ${tone.note}"></button>`).join(""); $$(".tone-swatch").forEach((button) => button.addEventListener("click", () => { state.gradientLightness = button.dataset.tone; update(); })); }
function makeOutput() { if (state.mode === "gradient") return gradientCss(); const base = state.text.trim() || "Tu nombre"; const transformed = styles[state.style].apply(base); return modeData[state.mode].format(transformed, state.style, state.emoji || "✦"); }

function renderStyles() { const choices = $("#style-choices"); choices.innerHTML = modeData[state.mode].styles.map((styleKey) => `<button class="style-choice ${state.style === styleKey ? "is-selected" : ""}" type="button" data-style="${styleKey}" role="radio" aria-checked="${state.style === styleKey}"><span>${styles[styleKey].apply("Dubicrack")}</span><small>${styles[styleKey].label}</small></button>`).join(""); $("#style-count").textContent = `${modeData[state.mode].styles.length} opciones`; $$(".style-choice").forEach((button) => button.addEventListener("click", () => { state.style = button.dataset.style; update(); })); }
function renderColors() { const palette = rolePalettes[state.roleType]; if (!palette.colors.some(([color]) => color === state.color)) state.color = palette.colors[0][0]; $("#palette-label").textContent = palette.label; $("#palette-description").textContent = palette.description; $("#color-swatches").innerHTML = palette.colors.map(([color, name]) => `<button class="swatch ${state.color === color ? "is-selected" : ""}" type="button" data-color="${color}" style="--swatch: ${color}" role="radio" aria-label="${name}, ${color}" aria-checked="${state.color === color}"></button>`).join(""); const selected = palette.colors.find(([color]) => color === state.color); $("#chosen-color").textContent = state.color; $("#chosen-color-name").textContent = selected?.[1] || "Color personalizado"; document.documentElement.style.setProperty("--role-color", state.color); $$(".swatch").forEach((button) => button.addEventListener("click", () => { state.color = button.dataset.color; update(); })); }
function renderGradient() { const css = gradientCss(); const colors = gradientColors(); const style = gradientStyles[state.gradientStyle]; const lightness = lightnessModes[state.gradientLightness]; $("#gradient-base").value = state.baseColor; $("#gradient-base-code").textContent = state.baseColor; $("#gradient-style").value = state.gradientStyle; $("#gradient-direction").value = state.gradientDirection; $("#gradient-lightness-note").textContent = lightness.note; $("#gradient-example-note").textContent = lightness.previewNote; $("#gradient-stop-count").textContent = state.gradientStops; $("#gradient-stops-help").textContent = state.gradientStops === 2 ? "Por defecto: 2 tonos — sombra y brillo — derivados." : `${state.gradientStops} tonos claros, medios y oscuros desde un solo color.`; $("#gradient-style-label").textContent = `${style.label} · ${lightness.label}`; $("#gradient-description").textContent = style.description; const colorNodes = colors.map((color, index) => `<span class="generated-color-dot" style="--generated-stop:${color}" role="img" aria-label="Color ${index + 1} de ${colors.length}"></span>`).join(""); $("#gradient-stop-list").innerHTML = `<div class="generated-color-rail" aria-label="Colores generados">${colorNodes}</div>`; $("#gradient-code-stops").innerHTML = `<div class="generated-color-rail" aria-label="Colores generados">${colorNodes}</div>`; $("#discord-preview").style.setProperty("--generated-gradient", css); renderToneSwatches(); }
function renderPresets() { $("#preset-list").innerHTML = presets.map((preset, index) => { const preview = preset.mode === "gradient" ? "Degradado de un color" : modeData[preset.mode].format(styles[preset.style].apply(preset.text), preset.style, preset.emoji || "💬"); return `<button class="preset-card" type="button" data-preset="${index}"><small>${preset.label}</small><strong>${preview}</strong><span>${preset.description}</span></button>`; }).join(""); $$(".preset-card").forEach((button) => button.addEventListener("click", () => applyPreset(presets[Number(button.dataset.preset)]))); }

function update(flash = true) {
  const output = makeOutput(); const config = modeData[state.mode]; const isGradient = state.mode === "gradient";
  $("#mode-kicker").textContent = config.kicker; $("#mode-title").textContent = config.title; $("#editor-help").textContent = config.help; $("#result-note").textContent = config.note;
  $("#name-input").value = state.text; $("#character-count").textContent = `${state.text.length}/46`; $("#preview-text").textContent = isGradient ? `${gradientStyles[state.gradientStyle].label} · ${lightnessModes[state.gradientLightness].label} · ${state.gradientStops} ${state.gradientStops === 1 ? "parada" : "paradas"}` : output; $("#output-text").textContent = output; $("#discord-preview").className = `discord-preview ${config.previewClass}`;
  $("#name-field").classList.toggle("is-hidden", isGradient); $("#emoji-field").classList.toggle("is-hidden", state.mode !== "channel"); $("#channel-type-field").classList.toggle("is-hidden", state.mode !== "channel"); $("#role-type-field").classList.toggle("is-hidden", state.mode !== "role"); $("#style-section").classList.toggle("is-hidden", isGradient); $("#color-panel").classList.toggle("is-hidden", state.mode !== "role"); $("#gradient-field").classList.toggle("is-hidden", !isGradient); $("#gradient-output-panel").classList.toggle("is-hidden", !isGradient); $("#gradient-example-copy").classList.toggle("is-hidden", !isGradient);
  $("#emoji-input").value = state.emoji; $("#role-type").value = state.roleType; $("#channel-type").value = state.channelType; $("#copy-button").innerHTML = `<span aria-hidden="true">⧉</span> ${isGradient ? "Copiar CSS" : "Copiar nombre"}`;
  if (!isGradient) renderStyles(); if (state.mode === "role") renderColors(); if (isGradient) renderGradient();
  if (flash) { const preview = $("#discord-preview"); preview.classList.add("is-flashing"); window.setTimeout(() => preview.classList.remove("is-flashing"), 180); }
}
function setMode(mode) { state.mode = mode; state.text = modeData[mode].initial; state.style = "script"; $$(".mode-button").forEach((button) => { const selected = button.dataset.mode === mode; button.classList.toggle("is-active", selected); button.setAttribute("aria-pressed", selected); }); update(false); }
function applyPreset(preset) { state.mode = preset.mode; if (preset.text !== undefined) state.text = preset.text; if (preset.style) state.style = preset.style; if (preset.emoji) state.emoji = preset.emoji; if (preset.roleType) state.roleType = preset.roleType; if (preset.channelType) state.channelType = preset.channelType; if (preset.baseColor) state.baseColor = preset.baseColor; if (preset.gradientStyle) state.gradientStyle = preset.gradientStyle; if (preset.stops) state.gradientStops = preset.stops; $$(".mode-button").forEach((button) => { const selected = button.dataset.mode === state.mode; button.classList.toggle("is-active", selected); button.setAttribute("aria-pressed", selected); }); update(); }
async function copyOutput() { const text = makeOutput(); try { await navigator.clipboard.writeText(text); } catch { const temporary = document.createElement("textarea"); temporary.value = text; document.body.appendChild(temporary); temporary.select(); document.execCommand("copy"); temporary.remove(); } const label = $("#copy-state"); const button = $("#copy-button"); label.textContent = "Copiado"; label.classList.add("is-copied"); button.innerHTML = "<span aria-hidden=\"true\">✓</span> Copiado"; window.setTimeout(() => { label.textContent = "Vista previa"; label.classList.remove("is-copied"); button.innerHTML = `<span aria-hidden="true">⧉</span> ${state.mode === "gradient" ? "Copiar CSS" : "Copiar nombre"}`; }, 1800); }

  $("#name-input").addEventListener("input", (event) => { state.text = event.target.value; update(); }); $("#emoji-input").addEventListener("input", (event) => { state.emoji = event.target.value; update(); }); $("#role-type").addEventListener("change", (event) => { state.roleType = event.target.value; state.color = rolePalettes[state.roleType].colors[0][0]; update(); }); $("#channel-type").addEventListener("change", (event) => { state.channelType = event.target.value; const suggestion = channelSuggestions[state.channelType]; state.emoji = suggestion.emoji; state.text = suggestion.name; update(); }); $("#emoji-suggest").addEventListener("click", () => { const suggestion = channelSuggestions[state.channelType]; state.emoji = suggestion.emoji; state.text = suggestion.name; update(); }); $("#gradient-base").addEventListener("input", (event) => { state.baseColor = event.target.value.toUpperCase(); update(); }); $("#gradient-style").addEventListener("change", (event) => { state.gradientStyle = event.target.value; state.gradientStops = gradientStyles[state.gradientStyle].defaultStops; update(); }); $("#gradient-direction").addEventListener("change", (event) => { state.gradientDirection = event.target.value; update(); }); $("#add-gradient-stop").addEventListener("click", () => { state.gradientStops = clamp(state.gradientStops + 1, 2, 7); update(); }); $("#remove-gradient-stop").addEventListener("click", () => { state.gradientStops = clamp(state.gradientStops - 1, 2, 7); update(); }); $("#gradient-random").addEventListener("click", () => { state.baseColor = `#${Math.floor(Math.random() * 0xFFFFFF).toString(16).padStart(6, "0").toUpperCase()}`; update(); }); $("#copy-button").addEventListener("click", copyOutput); $("#reset-button").addEventListener("click", () => setMode(state.mode)); $$(".mode-button").forEach((button) => button.addEventListener("click", () => setMode(button.dataset.mode))); renderPresets(); update(false);
